<?xml version="1.0"?>
<robot
    xmlns:gazebo="http://playerstage.sourceforge.net/gazebo/xmlschema/#gz"
    xmlns:model="http://playerstage.sourceforge.net/gazebo/xmlschema/#model"
    xmlns:sensor="http://playerstage.sourceforge.net/gazebo/xmlschema/#sensor"
    xmlns:body="http://playerstage.sourceforge.net/gazebo/xmlschema/#body"
    xmlns:geom="http://playerstage.sourceforge.net/gazebo/xmlschema/#geom"
    xmlns:joint="http://playerstage.sourceforge.net/gazebo/xmlschema/#joint"
    xmlns:controller="http://playerstage.sourceforge.net/gazebo/xmlschema/#controller"
    xmlns:interface="http://playerstage.sourceforge.net/gazebo/xmlschema/#interface"
    xmlns:rendering="http://playerstage.sourceforge.net/gazebo/xmlschema/#rendering"
    xmlns:physics="http://playerstage.sourceforge.net/gazebo/xmlschema/#physics"
    xmlns:xacro="http://www.ros.org/wiki/xacro"
    name="navgroup">

    <!-- Physical Constant Macros -->
    <xacro:property name="M_PI" value="3.1415926535897931" />

    <!-- Dimension Macros -->
<!--     <xacro:property name="carLength" value="0.3" />
    <xacro:property name="carWidth" value="0.15" />
    <xacro:property name="carHeight" value="0.1" />
    <xacro:property name="wheelRadius" value="0.06" />
    <xacro:property name="wheelWidth" value="0.025" /> -->

        <!-- Dimension Macros -->
    <xacro:property name="carLength" value="2.0" />
    <xacro:property name="carWidth" value="1.00" />
    <xacro:property name="carHeight" value="0.5" />
    <xacro:property name="wheelRadius" value="0.2125" />
    <xacro:property name="wheelWidth" value="0.125" />
    
    <!-- Physical Material Macros -->
    <material name="Red">
    	<color rgba="1.0 0 0 1.0"/>
    </material>
    <material name="Yellow">
        <color rgba="1.0 1.0 0 1.0"/>
    </material>
    <material name="Grey">
        <color rgba="0.25 0.25 0.25 1.0"/>
    </material>
    <material name="Green">
    	<color rgba="0 1.0 0 1.0"/>
    </material>
    <material name="Blue">
    	<color rgba="0 0 1.0 1.0"/>
    </material>
    <material name="Black">
    	<color rgba="0 0 0 1.0"/>
    </material>
    <material name="Aqua">
    	<color rgba="0 255 255 1.0"/>
    </material>


    <!-- Main body -->
    <link name="base_link">
        <inertial>
            <mass value="0.2" />
            <origin xyz="0 0 0" /> 
            <inertia  ixx="0.2" ixy="0.0"  ixz="0.0"  iyy="0.2"  iyz="0.0"  izz="0.2" />
        </inertial>
        <visual>
            <origin xyz="0 0 0.18" rpy="0 0 0" />
            <geometry>
                <box size="${carLength} ${carWidth} ${carHeight}" />
            </geometry>
            <material name="Grey"/>
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <geometry>
                <box size="${carLength} ${carWidth} ${carHeight}" />
            </geometry>
        </collision>
    </link>
    <gazebo reference="base_link">
        <material>Gazebo/Grey</material>
    </gazebo>
    
    <!-- Front link of Ackermann -->
    <!-- Joins to the Car body -->
    <joint name="front_joint" type="fixed">
    	<parent link="base_link"/>
    	<child link="front_link"/>
    	<origin xyz="0.603 0.0 -0.1"/>
    </joint>
    <link name="front_link">
        <inertial>
            <mass value="0.01" />
            <origin xyz="0 0 0" /> 
            <inertia  ixx="0.01" ixy="0.0"  ixz="0.0"  iyy="0.01"  iyz="0.0"  izz="0.01" />
        </inertial>
        <visual>
            <geometry>
                <box size="${carLength*0.05} ${carWidth} ${carHeight*0.05}" />
            </geometry>
            <material name="Aqua"/>
        </visual>
        <collision>
            <geometry>
                <box size="${carLength*0.05} ${carWidth} ${carHeight*0.05}" />
            </geometry>
        </collision>
    </link>
    <gazebo reference="front_link">
        <material>Gazebo/Black</material>
    </gazebo>
    
    <!-- a link aligned with the steer direction -->
    <joint name="steer_joint" type="revolute" >
        <limit lower="-0.31415" upper="0.31415" effort="100" velocity="10" />
        <axis xyz="0 0 1" />
        <parent link="front_link" />
        <child link="steer_link" />
        <origin xyz="0.0 0.0 0.0" rpy="0 0 0" />
    </joint>
    <link name="steer_link">
        <inertial>
            <mass value="0.01" />
            <origin xyz="0 0 0" />
            <inertia  ixx="0.01" ixy="0.0"  ixz="0.0"  iyy="0.01"  iyz="0.0"  izz="0.01" />
        </inertial>
        <visual>
            <origin xyz="-0.02 0 0" />
            <geometry>
                <box size="${carLength*0.1} ${carWidth*0.133} ${carHeight*0.05}" />
            </geometry>
            <material name="Black"/>
        </visual>
        <collision>
            <origin xyz="0.02 0 0" />
            <geometry>
                <box size="${carLength*0.1} ${carWidth*0.133} ${carHeight*0.05}" />
            </geometry>
        </collision>
    </link>
    <gazebo reference="steer_link">
        <material>Gazebo/Black</material>
    </gazebo>

    <!-- the left Ackermann bar -->
    <joint name="front_left_bar_joint" type="revolute" >
        <limit lower="-0.31415" upper="0.31415" effort="100" velocity="10" />
        <axis xyz="0 0 1" />
        <parent link="front_link" />
        <child link="front_left_bar_link" />
        <origin xyz="0.0 0.5525 0.0" rpy="0 0 0" />
    </joint>
    <link name="front_left_bar_link">
        <inertial>
            <mass value="0.01" />
            <origin xyz="0 0 0" />
            <inertia  ixx="0.01" ixy="0.0"  ixz="0.0"  iyy="0.01"  iyz="0.0"  izz="0.01" />
        </inertial>
        <visual>
            <origin xyz="-0.02 0 0" />
            <geometry>
                <box size="${carLength*0.1} ${carWidth*0.133} ${carHeight*0.05}" />
            </geometry>
            <material name="Black"/>
        </visual>
        <collision>
            <origin xyz="-0.02 0 0" />
            <geometry>
                <box size="${carLength*0.1} ${carWidth*0.133} ${carHeight*0.05}" />
            </geometry>
        </collision>
    </link>
    <gazebo reference="front_left_bar_link">
        <material>Gazebo/Black</material>
    </gazebo>

    <!-- the right Ackermann bar -->
    <joint name="front_right_bar_joint" type="revolute" >
        <limit lower="-0.31415" upper="0.31415" effort="100" velocity="10" />
        <axis xyz="0 0 1" />
        <parent link="front_link" />
        <child link="front_right_bar_link" />
        <origin xyz="0.0 -0.5525 0.0" rpy="0 0 0" />
    </joint>
    <link name="front_right_bar_link">
        <inertial>
            <mass value="0.01" />
            <origin xyz="0 0 0" />
            <inertia  ixx="0.01" ixy="0.0"  ixz="0.0"  iyy="0.01"  iyz="0.0"  izz="0.01" />
        </inertial>
        <visual>
            <origin xyz="-0.02 0 0" />
            <geometry>
                <box size="${carLength*0.1} ${carWidth*0.133} ${carHeight*0.05}" />
            </geometry>
            <material name="Black"/>
        </visual>
        <collision>
            <origin xyz="-0.02 0 0" />
            <geometry>
                <box size="${carLength*0.1} ${carWidth*0.133} ${carHeight*0.05}" />
            </geometry>
        </collision>
    </link>
    <gazebo reference="front_right_bar_link">
        <material>Gazebo/Black</material>
    </gazebo>

	<!-- the front left wheel -->
    <joint name="front_left_wheel_joint" type="continuous" >
        <axis xyz="0 1 0" />
        <parent link="front_left_bar_link" />
        <child link="front_left_wheel_link" />
        <origin xyz="0 0.04 0" rpy="0 0 0" />
    </joint>
    <link name="front_left_wheel_link">
        <inertial>
            <mass value="0.01" />
            <origin xyz="0 0 0" /> 
            <inertia  ixx="0.01" ixy="0.0"  ixz="0.0"  iyy="0.01"  iyz="0.0"  izz="0.01" />
        </inertial>
        <visual>
            <origin xyz="0 0 0" rpy="${M_PI/2} 0 0" />
            <geometry>
                <cylinder radius="${wheelRadius}" length="${wheelWidth}" />
            </geometry>
            <material name="Black"/>
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="${M_PI/2} 0 0" />
            <geometry>
                <cylinder radius="${wheelRadius}" length="${wheelWidth}" />
            </geometry>
        </collision>
    </link>
    <gazebo reference="front_left_wheel_link">
        <material>Gazebo/Black</material>
    </gazebo>

	<!-- the front right wheel -->
    <joint name="front_right_wheel_joint" type="continuous" >
        <axis xyz="0 1 0" />
        <parent link="front_right_bar_link" />
        <child link="front_right_wheel_link" />
        <origin xyz="0 -0.04 0" rpy="0 0 0" />
    </joint>
    <link name="front_right_wheel_link">
        <inertial>
            <mass value="0.01" />
            <origin xyz="0 0 0" /> 
            <inertia  ixx="0.01" ixy="0.0"  ixz="0.0"  iyy="0.01"  iyz="0.0"  izz="0.01" />
        </inertial>
        <visual>
            <origin xyz="0 0 0" rpy="${M_PI/2} 0 0" />
            <geometry>
                <cylinder radius="${wheelRadius}" length="${wheelWidth}" />
            </geometry>
            <material name="Black"/>
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="${M_PI/2} 0 0" />
            <geometry>
                <cylinder radius="${wheelRadius}" length="${wheelWidth}" />
            </geometry>
        </collision>
    </link>
    <gazebo reference="front_right_wheel_link">
        <material>Gazebo/Black</material>
        <turnGravityOff>false</turnGravityOff>
    </gazebo>

	<!-- the Ackerman bar -->
    <joint name="ackermann_joint" type="revolute" >
        <limit lower="-0.31415" upper="0.31415" effort="100" velocity="10" />
        <axis xyz="0 0 1" />
        <parent link="steer_link" />
        <child link="ackermann_bar_link" />
        <origin xyz="-0.04 0 0" rpy="0 0 0" />
    </joint>
    <link name="ackermann_bar_link">
        <inertial>
            <mass value="0.01" />
            <origin xyz="0 0 0" /> 
            <inertia  ixx="0.01" ixy="0.0"  ixz="0.0"  iyy="0.01"  iyz="0.0"  izz="0.01" />
        </inertial>
        <visual>
            <geometry>
                <box size="${carLength*0.05} ${carWidth} ${carHeight*0.1}" />
            </geometry>
            <material name="Black"/>
        </visual>
        <collision>
            <geometry>
                <box size="${carLength*0.05} ${carWidth} ${carHeight*0.1}" />
            </geometry>
        </collision>
    </link>
    <gazebo reference="front_link">
        <material>Gazebo/Black</material>
    </gazebo>
    <gazebo reference="ackermann_bar_link">
        <material>Gazebo/Blue</material>
    </gazebo>

	<!-- Gazebo Ackermann loop joints -->
    <gazebo>
      <joint:hinge name="ackermann_left_bar_joint">
        <body1>ackermann_bar_link</body1>
        <body2>front_left_bar_link</body2>
        <anchor>ackermann_bar_link</anchor>
        <axis>0 0 1</axis>
        <anchorOffset>0 0.5525 0</anchorOffset>
      </joint:hinge>
    </gazebo>
    <gazebo>
      <joint:hinge name="ackermann_right_bar_joint">
        <body1>ackermann_bar_link</body1>
        <body2>front_right_bar_link</body2>
        <anchor>ackermann_bar_link</anchor>
        <axis>0 0 1</axis>
        <anchorOffset>0 -0.5525 0</anchorOffset>
      </joint:hinge>
    </gazebo>
    
	<!-- the back left wheel -->
    <joint name="back_left_wheel_joint" type="continuous" >
        <axis xyz="0 1 0" />
        <parent link="base_link" />
        <child link="back_left_wheel_link" />
        <origin xyz="-0.603 0.5525 -0.1" rpy="0 0 0" />
    </joint>
    <link name="back_left_wheel_link">
        <inertial>
            <mass value="0.01" />
            <origin xyz="0 0 0" /> 
            <inertia  ixx="0.01" ixy="0.0"  ixz="0.0"  iyy="0.01"  iyz="0.0"  izz="0.01" />
        </inertial>
        <visual>
            <origin xyz="0 0 0" rpy="${M_PI/2} 0 0" />
            <geometry>
                <cylinder radius="${wheelRadius}" length="${wheelWidth}" />
            </geometry>
            <material name="Black"/>
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="${M_PI/2} 0 0" />
            <geometry>
                <cylinder radius="${wheelRadius}" length="${wheelWidth}" />
            </geometry>
        </collision>
    </link>
    <gazebo reference="back_left_wheel_link">
        <material>Gazebo/Black</material>
    </gazebo>
    
	<!-- the back right wheel -->
    <joint name="back_right_wheel_joint" type="continuous" >
        <axis xyz="0 1 0" />
        <parent link="base_link" />
        <child link="back_right_wheel_link" />
        <origin xyz="-0.603 -0.5525 -0.1" rpy="0 0 0" />
    </joint>
    <link name="back_right_wheel_link">
        <inertial>
            <mass value="0.01" />
            <origin xyz="0 0 0" /> 
            <inertia  ixx="0.01" ixy="0.0"  ixz="0.0"  iyy="0.01"  iyz="0.0"  izz="0.01" />
        </inertial>
        <visual>
            <origin xyz="0 0 0" rpy="${M_PI/2} 0 0" />
            <geometry>
                <cylinder radius="${wheelRadius}" length="${wheelWidth}" />
            </geometry>
            <material name="Black"/>
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="${M_PI/2} 0 0" />
            <geometry>
                <cylinder radius="${wheelRadius}" length="${wheelWidth}" />
            </geometry>
        </collision>
    </link>
    <gazebo reference="back_right_wheel_link">
        <material>Gazebo/Black</material>
    </gazebo>

    <!-- Ackermann plugin -->
    <gazebo>
      <controller:ackermann_plugin name="ackermann_controller"
			           plugin="libackermann_plugin.so">
	<alwaysOn>true</alwaysOn>
	<update>100</update>
	<updateRate>100.0</updateRate>
	<leftJoint>back_left_wheel_joint</leftJoint>
	<rightJoint>back_right_wheel_joint</rightJoint>
	<steerJoint>steer_joint</steerJoint>
	<wheelSeparationWidth>1.13</wheelSeparationWidth>
	<wheelSeparationLength>1.206</wheelSeparationLength>
	<wheelDiameter>0.425</wheelDiameter>
	<driveTorque>5</driveTorque>
	<steerTorque>5</steerTorque>
	<interface:position name="position_iface_0" />
	<robotNamespace>/</robotNamespace>
	<topicName>pilot/drive</topicName>
      </controller:ackermann_plugin>
      
     <canonicalBody>base_footprint</canonicalBody>

    <!-- this publishes empty joint_states due to no transmission, but
    triggering robot_state_publisher to publish tf between fixed joints in erratic,
    (e.g. base_laser_link for the base_scan frame) -->
    <controller:gazebo_ros_controller_manager name="gazebo_ros_controller_manager" plugin="libgazebo_ros_controller_manager.so">
      <alwaysOn>true</alwaysOn>
      <updateRate>100.0</updateRate>
      <interface:audio name="gazebo_ros_controller_manager_dummy_iface" />
    </controller:gazebo_ros_controller_manager>
      
    </gazebo>
    
        <joint name="laser_base_mount_joint" type="fixed">
            <origin xyz="0 0 0.05" rpy="0 0 0" /> 
            <parent link="base_link"/>
            <child link="laser_base_link"/>
        </joint>
        
        <link name="laser_base_link" type="fixed">
            <inertial>
                <mass value="0.1"/>
                <origin xyz="0 0 0.0"/>
                <inertia ixx="0.1" ixy="0" ixz="0" iyy="0.1" iyz="0" izz="0.1"/>
            </inertial>
            
            <visual>
                <origin rpy="0 0 0" xyz="1.0 0 0.4"/>
                <geometry>
                    <box size="0.18 0.18 0.18"/>
                </geometry>
                <material name="Blue"/>
            </visual>
            
            <collision>
                <origin rpy="0 0 0" xyz="1.0 0 0.4"/>
                <geometry>
                    <box size="0.18 0.18 0.18"/>
                </geometry>
            </collision>
        </link>
        
        <joint name="base_scan_joint" type="fixed" >
            <origin xyz="0 0 0.05" rpy="0 0 0" />
            <parent link="laser_base_link" />
            <child link="laser"/>
        </joint>
        
        <link name="laser" type="laser">
            <inertial>
                <mass value="0.1"/>
                <origin xyz="0 0 0.0"/>
                <inertia ixx="0.1" ixy="0" ixz="0" iyy="0.1" iyz="0" izz="0.1"/>
            </inertial>
            
            <visual>
                <origin rpy="0 0 0" xyz="0 0 0.014"/>
                <geometry>
                    <cylinder radius="0.0229" length="0.028"/>
                </geometry>
                <material name="Blue"/>
            </visual>
            
            <collision>
                <origin rpy="0 0 0" xyz="0 0 0.014"/>
                <geometry>
                    <cylinder radius="0.0229" length="0.028"/>
                </geometry>
            </collision>
        </link>

        <gazebo reference="laser">
            <sensor:ray name="laser">
                <rayCount>683</rayCount>
                <rangeCount>683</rangeCount>
                <laserCount>1</laserCount>
                
                <origin>0.0 0.0 0.0</origin>
                <displayRays>false</displayRays>
                
                <minAngle>0</minAngle>
                <maxAngle>180</maxAngle>
                
                <minRange>0.06</minRange>
                <maxRange>4.0</maxRange>
                <resRange>0.001</resRange>
                <updateRate>10.0</updateRate>
                
                <controller:gazebo_ros_laser name="gazebo_ros_base_scan_link_controller" plugin="libgazebo_ros_laser.so">
                    <gaussianNoise>0.005</gaussianNoise>
                    <alwaysOn>true</alwaysOn>
                    <updateRate>10.0</updateRate>
                    <topicName>base_scan/scan</topicName>
                    <frameName>laser</frameName>
                    <interface:laser name="gazebo_ros_laser_iface"/>
                </controller:gazebo_ros_laser>
            </sensor:ray>
        </gazebo>
        
        <gazebo reference="laser_base_link">
            <material>Gazebo/Blue</material>
        </gazebo>
	
        <gazebo reference="laser">
            <material>Gazebo/Blue</material>
        </gazebo>
</robot>
